### PR TITLE
Add drupal-rector to tooling.

### PR DESCRIPTION
**Pull request by DuaelFr**
[Drupal Rector](https://github.com/palantirnet/drupal-rector) is a powerful tool to automate fixing deprecated Drupal code.

Having it in this project would help a lot!

### CODE REVIEW

**Comment by gitressa** [comment]
That would be nice. Should it also be added to Drupal 10?

**Comment by DuaelFr** [comment]
Sure! It should be as simple as a cherry-pick :)

**Comment by gitressa** [comment]
Thanks, sounds good! Perhaps it could be added in the Issue summary, so  we remember it?

- [ ] Add in Drupal 10 (cherry pick)

**Comment by reynoldsalec** [comment]
If @gitressa or @DuaelFr want to add this to 10.x, sounds like that would be beneficial, thanks for the contribution!

**Pull request merged**
